### ISSUE TITLE
Releasing mouse outside of window does not end drag state

### ISSUE THREAD

**Issue by Gyoshi** [ppy/osu-framework#5788] opened 2023-05-13 12:11 UTC
Tested in both osu! and osu.Framework.Tests.exe, on Desktop (windows 11)

In windowed and borderless windowed, if you drag but release mouse button outside of window:
Mouse stays lit up (in osu!) and Drawables being interacted with remain active until clicking and releasing again *inside* the window.

**Comment by bdach** [comment] 2023-05-14 09:43
Details on which platform this was tested on would be helpful.

**Comment by Gyoshi** [comment] 2023-05-14 10:51
Windows 11

**Comment by hwabis** [comment] 2023-07-07 03:32
Would the correct behavior be for the cursor in o!f to be released as soon as the mouse leaves the window? (Or would the cursor in o!f release only when the mouse is released, even when outside the window? I'm not familiar with input handling so I don't even know if that's possible.)

**Comment by peppy** [comment] 2023-07-07 03:50
Doesn't happen on macOS, does on windows.

**Comment by FreezyLemon** [comment] 2023-08-20 19:31
This can be reproduced in TestSceneInputManager. There is a toggle for the MouseHandler's `UseRelativeMode`, and I can reproduce that with relative mode disabled, this bug does not occur. WIth relative mode enabled, it does.

It looks like it's been reported before: #4055. The PR closing it (#5163) states that it only partially fixes this behaviour, but the issue was closed anyways.

The reason for disabling this auto-capture behaviour when relative mode is enabled is explained in the code:
https://github.com/ppy/osu-framework/blob/102ae9498b215cc4eb2150a8e63c5563a58dafb3/osu.Framework/Platform/SDL2Window_Input.cs#L57-L71

**Comment by FreezyLemon** [comment] 2023-08-24 21:52
Note that I can also reproduce this on Linux.

**Comment by gadielisawesome** [comment] 2023-09-30 05:58
I can reproduce this sometimes on Android when using osu in splitscreen.

**Closed** 2023-10-30 04:18 UTC
Labels: priority:0, area:input

**Comment by Susko3** [comment] 2023-10-30 09:34
@gadielisawesome please open a new issue for android, with additional info and a screen recording. If you can, check how it behaves with relative mode turned on and off.

**Comment by gadielisawesome** [comment] 2023-11-13 02:28
It's been 2 months. I no longer own an Android device, so I cannot reproduce this issue.
