### ISSUE TITLE
FlowContainer layout doesn't get invalidated in some scenarios

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu-framework#2562] opened 2019-06-20 11:36 UTC
When scaling and resizing a `Container` that contains a `FillFlowContainer` simultaneously , the layout of the flow will not be invalidated. The position of each `Drawable` will not be updated until you force an invalidation.

Test case to visualize:

```csharp
public class TestSceneFillFlowContainer : TestScene
{
    public TestSceneFillFlowContainer()
    {
        TestContainer testContainer;
        Add(testContainer = new TestContainer
        {
            RelativeSizeAxes = Axes.Both,
            Child = new FillFlowContainer
            {
                RelativeSizeAxes = Axes.Both,
                Height = 0.25f,
                Children = new[]
                {
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Beige,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Bisque,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Aquamarine,
                        Width = 0.2f,
                    },
                    new Box
                    {
                        RelativeSizeAxes = Axes.Both,
                        Colour = Color4.Cornsilk,
                        Width = 0.2f,
                    },
                }
            }
        });

        AddSliderStep("Adjust scale", 0.5, 1.5, 1.0, b => testContainer.AdjustScale((float)b));
        AddStep("Invalidate layout", () => testContainer.Invalidate());
    }

    private class TestContainer : Container<Drawable>
    {
        public void AdjustScale(float scale = 1.0f)
        {
            this.ScaleTo(new Vector2(scale));
            this.ResizeTo(new Vector2(1 / scale));
        }
    }
}
```

**Comment by smoogipoo** [comment] 2019-06-20 12:03
Duplicate of #223 (added as a comment).

**Closed by smoogipoo** 2019-06-20 12:03 UTC
