### ISSUE TITLE
Spectator cursor goes wild in Autopilot

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu-framework#4762] opened 2021-09-07 02:09 UTC
I went into spectator mode to see how they were doing,
The autopilot player's cursor went insane, then stabilized randomly, then I reloaded spectator and it resumed glitching,

https://user-images.githubusercontent.com/40531871/132273306-241b1142-bcbc-4b75-8405-be0c43a96338.mp4
Lazer v2021.828.0

**Comment by frenzibyte** [comment] 2021-09-07 02:11
Not only this is in the wrong repo (should be in [ppy/osu](https://www.github.com/ppy/osu)), this is also a duplicate of https://github.com/ppy/osu/issues/14420.

**Closed by frenzibyte** 2021-09-07 02:11 UTC
