### ISSUE TITLE
Range exception when deleting word in textbox while empty

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu-framework#3173] opened 2020-01-13 10:05 UTC
Steps:

1. Get any empty textbox.
2. Press `Ctrl+Backspace` or `Ctrl+Del`
3. Exception!

Consistently reproduced with all textboxes in osu!

```
2020-01-13 09:59:28: System.ArgumentException: '0' cannot be greater than -1.
2020-01-13 09:59:28: at System.Math.ThrowMinMaxException[T](T min, T max)
2020-01-13 09:59:28: at osu.Framework.Graphics.UserInterface.TextBox.OnPressed(PlatformAction action)
2020-01-13 09:59:28: at osu.Framework.Input.Bindings.KeyBindingContainer`1.<>c__DisplayClass19_0.<PropagatePressed>b__1(IKeyBindingHandler`1 d)
2020-01-13 09:59:28: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2020-01-13 09:59:28: at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
2020-01-13 09:59:28: at osu.Framework.Input.Bindings.KeyBindingContainer`1.PropagatePressed(IEnumerable`1 drawables, T pressed, Single scrollAmount, Boolean isPrecise)
2020-01-13 09:59:28: at osu.Framework.Input.Bindings.KeyBindingContainer`1.handleNewPressed(InputState state, InputKey newKey, Boolean repeat, Nullable`1 scrollDelta, Boolean isPrecise)
2020-01-13 09:59:28: at osu.Framework.Input.Bindings.KeyBindingContainer`1.Handle(UIEvent e)
2020-01-13 09:59:28: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
2020-01-13 09:59:28: at osu.Framework.Input.InputManager.PropagateBlockableEvent(IEnumerable`1 drawables, UIEvent e)
2020-01-13 09:59:28: at osu.Framework.Input.InputManager.handleKeyDown(InputState state, Key key, Boolean repeat)
2020-01-13 09:59:28: at osu.Framework.Input.InputManager.HandleKeyboardKeyStateChange(ButtonStateChangeEvent`1 keyboardKeyStateChange)
2020-01-13 09:59:28: at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
2020-01-13 09:59:28: at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
2020-01-13 09:59:28: at osu.Framework.Input.InputManager.Update()
2020-01-13 09:59:28: at osu.Framework.Input.PassThroughInputManager.Update()
2020-01-13 09:59:28: at osu.Framework.Graphics.Drawable.UpdateSubTree()
2020-01-13 09:59:28: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
2020-01-13 09:59:28: at osu.Framework.Platform.GameHost.UpdateFrame()
2020-01-13 09:59:28: at osu.Framework.Threading.GameThread.ProcessFrame()
2020-01-13 09:59:28: at osu.Framework.Threading.GameThread.runWork()
```

**Comment by turbedi** [comment] 2020-01-13 10:10
Duplicate of ppy/osu#7505, already fixed with #3171. Issue can be closed.

**Closed** 2020-01-13 10:10 UTC
