### ISSUE TITLE
Changing screen modes in a certain order causes the window border to disappear

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#4098] opened 2020-12-14 14:58 UTC
Changing screen modes in the following order causes the window border to disappear (on Windows 10):

`Windowed`→`Borderless`→`Fullscreen`→`Windowed`.
It's very easy to reproduce for people who use <kbd>Alt</kbd>+<kbd>Enter</kbd> to switch between those modes.

(**Can be fixed by switching between borderless and windowed mode**)

![example SDL](https://user-images.githubusercontent.com/43073074/102095720-2676d980-3e24-11eb-97f1-0add728de131.png)

Works fine with `--tk` argument:

![example tk](https://user-images.githubusercontent.com/43073074/102096201-b9b00f00-3e24-11eb-9fb0-0a5e90585afd.png)

Tested on the latest osu!lazer release ([2020.1212.0](https://github.com/ppy/osu/releases/tag/2020.1212.0)).

**Comment by Gabixel** [comment] 2020-12-14 15:10
It actually looks like it's still in fullscreen/borderless: I can't use shortcuts like <kbd>Windows</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> to change its size, and I can't right-click its window preview to show options like _drag_ or _maximize_.

**Comment by bdach** [comment] 2020-12-14 16:02
Probably related / partial duplicate of #4097

**Closed** 2020-12-22 02:52 UTC
Labels: area:platform, platform:windows
