### ISSUE TITLE
OS cursor is invisible while dragging

### ISSUE THREAD

**Issue by ekrctb** [ppy/osu-framework#1679] opened 2018-07-03 06:56 UTC
Press any mouse button on the game window and move mouse to outside of the game window.
Expected: OS cursor is visible.
Actual: OS cursor is invisible while pressing mouse button.
Note: Only tested on Windows. Both raw/non-raw input are affected. Confine cursor option is set to off/only full screen (obviously to move outside of the game window).

**Comment by peppy** [comment] 2018-07-03 06:57
I actually think I intentionally did it this way. Open for discussion on what is the expected behaviour.

**Comment by LastExceed** [comment] 2018-08-13 13:35
Confirmed on Linux (gnome)

On the one hand hiding the OS cursor in this case clarifies that although the window was left, the user is still interacting with it and not the desktop (or another window in the background), but on the other hand it is difficult to understand whats going on if this happens accidently as finding the way back to the window is difficult without releasing the mouse button, which could potentially mean an unwanted interaction.

I'd vote for showing the OS cursor.

**Comment by Morilli** [comment] 2018-08-13 18:30
I personally feel like the OS cursor being shown feels pretty natural to me.

**Comment by peppy** [comment] 2018-09-06 02:00
I still stand by our implementation (which is opposite to this). Unfortunately it doesn't work on macOS currently.

**Comment by Joehuu** [comment] 2020-11-28 06:38
Seems to be resolved in SDL. Looking at the discussion though, I would also want show the cursor (partly because stable does that).

**Comment by Joehuu** [comment] 2020-12-01 21:52
Above comment was on Windows 10.

Seems to still happen on Linux (Ubuntu 20.04 to be exact).

**Comment by Susko3** [comment] 2022-05-08 10:38
With #5163, the cursor is automatically captured, and is invisible (only if `CursorState` is `Hidden`).
This does seem a bit strange, as the cursor will "randomly" appear outside the window when left click is released.

To note, the cursor must be hidden for relative mode to work, so showing the cursor when `Sensitivity != 1` will not feel right.

**Comment by peppy** [comment] 2022-05-09 08:27
As I said in a much earlier post, I do think this behaviour is fine. If the game captures a drag it should keep the cursor invisible until the drag ends.

Shall we close this for now?

**Comment by Susko3** [comment] 2022-05-09 08:43
Fine to close, as this issue is discussing what behaviour we want, and going forward the cursor will have to be hidden.

Relative mode enabled doesn't hide the cursor, but this will get fixed with #4055. No need to have two issues tracking the same thing.

**Closed by Susko3** 2022-05-09 08:43 UTC
Labels: proposal, area:input, low priority, fixed-in-sdl
