### ISSUE TITLE
Negative delta provided by FpsDisplay

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#696] opened 2017-05-04 07:21 UTC
Not sure how this is happening... but it causes crashes at random.

![image](https://cloud.githubusercontent.com/assets/191335/25693699/b18dba34-30e5-11e7-80a0-9f4d12630419.png)

![image](https://cloud.githubusercontent.com/assets/191335/25693708/bda67f86-30e5-11e7-8c6e-c2bfe79bd57d.png)

**Comment by jai-sharma** [comment] 2017-05-31 15:48
Is this issue still open, or was it fixed by #746 ?

**Comment by FreezyLemon** [comment] 2018-01-09 07:29
It might be related to [this](https://stackoverflow.com/a/7520006/7928072) bug in the .NET Framework (see that answer point 1).
Seems to be a very low-level issue, if this is the cause.

**Comment by Pizzabelly** [comment] 2019-11-07 03:32
I think the issue is caused by subtracting SleptTime when the slept time is already accounted for in the ThrottledFrameClock code by updating CurrentTime after the sleep.

https://github.com/ppy/osu-framework/blob/971487974911595ea52cdd9ddbdd8852ae441a0b/osu.Framework/Graphics/Performance/FrameTimeDisplay.cs#L81
https://github.com/ppy/osu-framework/blob/971487974911595ea52cdd9ddbdd8852ae441a0b/osu.Framework/Timing/ThrottledFrameClock.cs#L61-L64

After I removed that part I always get positive frame times

**Closed** 2019-11-08 09:28 UTC
Labels: bounty
