### ISSUE TITLE
Error on dynamic recompilation

### ISSUE THREAD

**Issue by metametamoon** [ppy/osu-framework#4699] opened 2021-08-20 10:02 UTC
dotnet version: 6.0.100-preview.6.21355.2
OS: Windows 10
osu-framework: 2021.728.0

I created a default osu-framework project using a template with a spinning box and tried to stop the rotation (by commenting the corresponding line) while running visual tests in debug mode (no debugger attached). However, the dynamic recompilation failed (the console log is attached to this issue). Installing NuGet.ProjectModel and System.ComponentModel from the NuGet site doesn't seem to help.
[log.txt](https://github.com/ppy/osu-framework/files/7020718/log.txt)

**Comment by jai-x** [comment] 2021-08-20 10:11
Possible duplicate of https://github.com/ppy/osu-framework/issues/4512

If you're using an installed version of `dotnet` that's managed by a version manager like `asdf`, it does not install all the required dependencies and you should use the system provided `dotnet` or download and install manually from the dotnet website.

**Comment by Kremator1007** [comment] 2021-08-20 10:24
I do not use any version manager though. I reinstalled dotnet from the microsoft site just in case, and the problem is still there (same exception is thrown).

**Comment by jai-x** [comment] 2021-08-20 10:42
Would you be able to post your system specs and the version of dotnet you are running?

**Comment by Kremator1007** [comment] 2021-08-20 11:29
I edited the comment to include the mentioned details.

**Comment by jai-x** [comment] 2021-08-20 11:32
I would try downgrading to use dotnet 5.x instead of dotnet 6-preview. I don't believe the framework has been tested to work on dotnet 6 yet.

**Comment by Kremator1007** [comment] 2021-08-20 12:08
I downgraded; unfortunately, the error perseveres. Manual installing of packages doesn't help still.

**Comment by bdach** [comment] 2021-08-21 17:30
I've looked into this some more and it looks as if having the template game target `net5.0` alongside `netstandard2.1` fixes this, but I have no idea why. Upon adding some logging in `RoslynTypeReferenceBuilder`, something seems to trigger the game project into attempting to load `System.ComponentModel.Composition`, which somehow works with lazer (even though it doesn't target `net5.0` explicitly), but fails with the templates.

In the end the game seems to find the dll in `/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.8/System.ComponentModel.dll` which is a bit weird. Maybe the project has to be aware of `net5.0`'s existence to see some assembly redirects or something? No idea.

**Comment by Kremator1007** [comment] 2021-08-22 12:57
In my case targeting net5.0 alongiside netstandard2.1 also fixes the issue.

**Comment by bdach** [comment] 2022-02-17 21:30
So after the .NET 6 bump dynamic recompilation stopped working entirely everywhere for me (as in, not only in templates as described above), with

```
[runtime] 2022-02-17 21:26:47 [error]: Error with dynamic compilation!
[runtime] 2022-02-17 21:26:47 [error]: System.IO.FileLoadException: Could not load file or assembly 'NuGet.ProjectModel, Version=6.0.0.280, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
[runtime] 2022-02-17 21:26:47 [error]: File name: 'NuGet.ProjectModel, Version=6.0.0.280, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

Is anyone else seeing this? After bumping the package in question (as well as `Microsoft.CodeAnalysis.*` packages, as that started spewing next), and fixing a few new compiler warnings, recompilation started working again - but I am curious whether it's something with my box or it is just plain broken.

Changes that make recompilation work again for me are on the following branch to preview: https://github.com/ppy/osu-framework/compare/master...bdach:dynamic-compilation-net-6?expand=1

**Comment by dekrain** [comment] 2022-02-17 22:06
IIRC I was getting this also on .NET 5, so I just wrapped the resolver in a try/catch block if an assembly is not found.

**Comment by bdach** [comment] 2022-02-17 22:27
> so I just wrapped the resolver in a try/catch block if an assembly is not found.

that is... not a solution by any means.

> While I was testing my DrawVisualiser extension, this recompilation error occurred:

and this one is off topic when it comes to this issue thread.

**Comment by bdach** [comment] 2022-02-18 00:21
>> so I just wrapped the resolver in a try/catch block if an assembly is not found.
>
> that is... not a solution by any means.

I'm actually going to backtrack on this slightly because while installing new packages helped framework-side, on a game-side framework checkout there are more problems with missing `SQLite.PCL` binaries and that may not be so easy to fix properly. So adding a fallback catch path (*with appropriate logging*) may be best at least for now?

**Closed** 2022-02-21 05:19 UTC
Labels: area:tooling
