### ISSUE TITLE
Visual problems switching between Fullscreen/Borderless and Windowed screen mode

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-framework#2214] opened 2019-03-02 13:22 UTC
**Describe your problem:** There's this weird visual problem when trying to maximize the osu!lazer window size after switching between fullscreen/borderless and windowed mode.

**Screenshots or videos showing encountered issue:**
- [Video](https://streamable.com/j9tvc)

- Here's a screenshot:
![screenshot example](https://user-images.githubusercontent.com/43073074/53682451-23196900-3cf6-11e9-86b6-55bf2b1bef9f.png)

**osu!lazer version:** 2019.302.0.0

**Computer Specifications:**
- OS → Windows 10 Home (x64)
- GPU → GeForce GTX 1060 6GB
- CPU → AMD Ryzen 5 1600 Six-Core
- RAM → HyperX FURY 16GB (8x2) DDR4
- Screen Resolution → [1: 1920x1080] [2: 1440x900]

**Comment by Gabixel** [comment] 2020-11-05 13:54
Just tested this one on the latest version of osu!lazer (2020.1031.0), and seems to be fixed **using SDL**. (I didn't test on previous versions, but.. good to know that it's fixed, I guess)

**Comment by Joehuu** [comment] 2020-12-04 08:44
Also can't reproduce on osuTK in the first place, @Gabixel. Can you confirm this is still fixed as of latest lazer release?

**Comment by Gabixel** [comment] 2020-12-04 08:54
Yes, but.. no: this specific issue looks fixed with the latest release of osu!lazer, but now there's a different one (but still related to switching between windowed and fullscreen/borderless).

I guess this one can be closed. I will open another issue for the new one.

**Closed** 2020-12-04 09:01 UTC
Labels: area:graphics, fixed-in-sdl, platform:windows
