### ISSUE TITLE
iOS deployment issues (summary)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-framework#4677] opened 2021-08-10 04:58 UTC
I'm making this issue just to document the current issues we are facing that are inhibiting iOS deployment of osu!. We are looking to seek external help for this as there is no one with the time/expertise combo local to the project.

# Critical

## ~~AOT failure (https://github.com/ppy/osu/issues/13302)~~ [Resolved]

This has been reported upstream, along with a solution by @frenzibyte involving a package rollback. Needs a second confirmation on the xamarin-side issue (https://github.com/xamarin/xamarin-macios/issues/12353) to hopefully get the ball rolling (as this does not look like our issue).

![](https://cdn.discordapp.com/attachments/589331078574112768/872728621490536469/unknown.png)

## ~~Testing of new bass library version~~ [Resolved]

We recently updated to ManagedBass 3.0 to consume newer underlying un4seen bass libraries (https://github.com/ppy/osu-framework/pull/4291). Since this we are seeing a compile time version mismatch. This looks to have been attempted to be fixed upstream (https://github.com/ManagedBass/ManagedBass/pull/93) but this fix does not work for us. It also seems like an incorrect way to fix this issue.

```csharp
warning MSB3243: No way to resolve conflict between "ManagedBass, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" and "ManagedBass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". Choosing "ManagedBass, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null" arbitrarily. 
```

Testing with a local nupkg of ManagedBass (and the two addons we use) will be required to get all three working together, at which point a pull request needs to be made upstream to fix the actual issue.

Audio also needs to be tested to still work (we have not been able to compile to even test this since the BassMix conversion).

## ~~Cross nupkg testing~~ [Fulfilled]

osu! needs to be re-tested with all the above fixed.

## Deadlock investigation

We already attempted to fix random deadlocks during the startup sequence but have not yet understood a solid fix for it. We are also unsure if it's something our end or not. This needs a deeper investigation, either via somehow getting a deadlock to happen in a thread dumpable state, or using another method of diagnosis.

Previous fixes were centered around iOS having a `SynchronizationContext` while other platforms don't, and as we were doing some incorrect `async/await` it was causing deadlocks. Not sure if this is still the issue (we have fixed a few more cases since, see https://github.com/ppy/osu/issues/13231).

Keep in mind that we are not sure whether this is still an issue. It only reproduced on `Release` builds in the past so that is imperative to consider when attempting to reproduce.

# Nice to fix

## ~~Native library package duplication (https://github.com/ppy/osu-framework/issues/3030)~~ [Resolved]

A fix for this has been attempted, but a lack of proper testing (especially across the nuget package border) has meant it has not yet seen light of day.

**Comment by frenzibyte** [comment] 2021-08-23 13:37
To update on the mentioned ManagedBass library versioning issue above, ManagedBass have recently published a new release (v3.1.0) which seems to have mostly fixed the issue with version conflicts, after updating all relevant packages to it.

But while that has been resolved, a new completely different issue arrived in the process, one that still blocks from building iOS projects:
![image](https://user-images.githubusercontent.com/22781491/130451201-b14eeb30-5ef1-4994-a5cd-3ae2dba3a33f.png)
(full output in `-v -v -v -v` is so massive it would be easier to attempt building and getting it rather than attaching it here, but I'll attempt to do so on request)

It's a native linking failure caused by a number of symbols referenced in the native `libbassmix.a` library. 

I've also got these warnings that look to be directly relevant to the error, as I've never got them when rewinding back to https://github.com/ppy/osu-framework/commit/011d2ecc24c4be584dcbe65f966809b414055498, a commit that's directly behind the bassmix merge commit):
```
MTOUCH : warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'winmm' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'User32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'user32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'Kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'SHCore' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libSDL2' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libX11.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libXxf86vm.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libXcursor.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libXrandr.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'dl' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libGL.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libXi.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libXinerama.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'shell32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'user32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'User32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'winmm' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'gdi32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'dwmapi' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'user32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'hid' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'OPENGL32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'gdiplus' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libSDL2-2.0.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdrm.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libgbm.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libkms.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libinput.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libc.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libudev.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'EGL' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'opengl32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'GLESv2' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'GLESv1_CM' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'Microsoft.DiaSymReader.Native.x86' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'Microsoft.DiaSymReader.Native.amd64' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'mscoree' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'dbgeng' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'msvcrt' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'version' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'SDL2' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl.so' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'libdl' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'stbi' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'bassmix' might require additional -framework=XXX or -lXXX instructions to the native linker
MTOUCH : warning MT5215: References to 'bass_fx' might require additional -framework=XXX or -lXXX instructions to the native linker
```
(notice `MTOUCH : warning MT5215: References to 'bassmix' might require additional -framework=XXX or -lXXX instructions to the native linker`)

My guess on the matter would be that the framework project never had the chance to reach the native linking stage on iOS platform after the bassmix changes have been merged, and this issue was hiding from there all this time up till now.

I've attempted reproducing this in an isolated project, testing with different GCC flags / linking ways, but to no avail, unfortunately. It might potentially depend on referencing from a .NET Standard project, or other quirks the framework project currently have. (note that I've been building the `SampleGame.iOS` project to test this, in case it's any relevant)

**Comment by frenzibyte** [comment] 2021-08-23 13:50
As for the mentioned AOT failure (<https://github.com/ppy/osu/issues/13302>), it turns out to be an underlying mono issue, and that for the time being we'll have to workaround this issue locally, by one of the following:
 - Downgrade to version 2.0.161401 which gets AOT'd correctly. 
     - It seems the library upgrade happened in this PR https://github.com/ppy/osu-framework/pull/4316 and all other upgrades came regularly from dependabot, so there should potentially be no issues with downgrading.
 - Follow the solutions mentioned in https://github.com/xamarin/xamarin-macios/issues/12353#issuecomment-899540740
     - As it was pointed there that Xamarin projects aren't supposed to reference such package, it'll make sense going forward to either use `#if` preprocessors or replace it with stubs.

**Comment by frenzibyte** [comment] 2021-11-22 21:26
All issues have now been resolved, couldn't get any deadlocks on long-time osu! sessions. Will close this now, deadlock issues can be reported separately if they still persist.

**Closed by frenzibyte** 2021-11-22 21:26 UTC
Labels: platform:iOS
