### ISSUE TITLE
Ctrl-F1 doesn't work on all systems

### ISSUE THREAD

**Issue by Mempler** [ppy/osu-framework#3043] opened 2019-11-27 09:29 UTC
This is mostly due to a bug in OsuTK itself as there is nothing wrong in osu.Framework.

**Comment by peppy** [comment] 2019-11-27 09:57
For some data points, this doesn't happen to me on my windows 10 VM, nor macOS. It does happen on my native windows 10 PC (requiring Ctrl-Alt-F1 to activate).

If you have confirmed it's an `OsuTK` issue, please provide documentation how you ascertained that.

**Comment by Mempler** [comment] 2019-11-27 10:16
I've basically took the long route and reproduced that issue by:
> * Creating a new project using the latest [Source](https://github.com/ppy/osuTK) code,
> * Added some logging:
> ```cs
> using System;
> using osuTK;
> 
> namespace TestProject
> {
>     internal static class Program
>     {
>         private static void Main(string[] args)
>         {
>             var gameWindow = new GameWindow();
> 
>             gameWindow.KeyDown += (sender, key) =>
>             {
>                Console.WriteLine($"CTRL: {key.Control} Key: {key.Key}");
>             };
>             
>             gameWindow.Run();
>             Console.WriteLine("Hello World!");
>         }
>     }
> }
> ```
> * Found out that no key event is getting fired when pressing CTRL + F1
> * Searched deeper and went into [this](https://github.com/ppy/osuTK/blob/77081991883230344eec215f80e6ee8ad76132fc/src/osuTK/Platform/Windows/WinGLNative.cs#L711) File.
> * Hooked up some logging, and it seems like that [this](https://github.com/ppy/osuTK/blob/master/src/osuTK/Platform/Windows/WinGLNative.cs#L809-L817) never gets called if CTRL + F1 is pressed.

**Comment by swoolcock** [comment] 2019-11-27 10:17
Would be interesting to also verify that this is a non-issue with the SDL2 backend.

**Comment by huoyaoyuan** [comment] 2019-11-27 11:25
After a quick search, someone mentioned it may be globally registered to some other programs. [Chinese source](https://jingyan.baidu.com/article/e73e26c0a7317f24adb6a704.html)

**My Windows 10 native dev machine can fire Ctrl+F1 normally.** You'd better investigate with some tool showing global registered hotkeys.

**Comment by peppy** [comment] 2019-11-27 16:38
Note that this isn't windows only, as @smoogipoo is able to reproduce on macOS (I am not, though).

**Comment by bdach** [comment] 2019-11-27 21:29
I've briefly tested this, since it reproduces for me. It also reproduces with SDL. In fact, it looks like at least *my* Windows install is busted somehow. I do not say this lightly, [here's some video evidence](https://streamable.com/mv209).

Context for what you're looking at:
* visual test browser in the background,
* the very windows-95-looking thing is [spy++](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-start-spy-increment?view=vs-2019), hooked up to receive all winapi keyboard messages from all other windows,
* keyboard visualiser on the bottom right is nohboard.

To sum up the video: for some reason pressing <kbd>Ctrl</kbd>+<kbd>F1</kbd> *or* <kbd>Ctrl</kbd>+<kbd>F3</kbd> leads to *`WM_KEYDOWN` events not being generated for `VK_F1` or `VK_F3` **at all***, but if you add <kbd>Alt</kbd> *it miraculously starts working again*. All the other F keys work fine. And since the keybindings fire at key down and not up, this is why the shortcut breaks.

Before you ask: yes, it reproduces without nohboard on, and no, it shouldn't be a global hotkey of something else, since the preset for capturing keyboard events also includes `WM_HOTKEY`. I suppose next step would be to start killing all of my processes one by one to make sure it really is the OS. Or safe mode, I dunno.

Windows 10.0.18362 if anyone wants to compare version numbers, by the way.

**Comment by swoolcock** [comment] 2019-11-27 21:40
I had the issue on macOS until I turned off these default system shortcuts:

<img width="668" alt="Screen Shot 2019-11-28 at 8 07 12 am" src="https://user-images.githubusercontent.com/2331297/69761156-73a2f180-11b6-11ea-95df-612016fbd911.png">

**Comment by bdach** [comment] 2019-11-27 22:44
@Mempler and I had the [parsec](https://parsecgaming.com/) game streaming client installed on our windows machines, and it seems they do horrible things with keyboard hooks globally (probably suppressing the events altogether) even when they're not actively streaming a game. So that should be the windows case resolved for us both, not sure about @peppy's.

**Comment by peppy** [comment] 2019-11-28 01:55
I am also running parsec on the only machine Ctrl-F1 doesn't work for me. Nice catch. I've sent an email to then and would suggest anyone else running into this potentially does the same to make them aware of the issue.

**Comment by boxerbk** [comment] 2019-11-28 03:44
Hey all. Sorry for the confusion this caused. Dean emailed me about this thread. Parsec captures Ctrl + F1 and Ctrl + F3 globally because you need to be able to accept / kick connections from anywhere when they're happening as a host. You can either shut down Parsec completely or change the hotkeys for these events in the Parsec settings. Thanks, Benjy

**Comment by peppy** [comment] 2019-11-28 03:49
@boxerbk thanks for the response.

is there any chance these global keys could be disabled when no one is connected? it's quite common to run parsec in the background but seldom use it (leaving it open so your PC is available for remote connection), at which point it becomes a nuisance to have to manually open / close it each time.

**Comment by boxerbk** [comment] 2019-11-28 04:16
@peppy That's a good recommendation. the reason they're on by default in the background is because the Parsec host is waiting for a connection at all times. When someone initiates the connection to the host, you need to be able to press Ctrl + F1 to accept them. We could potentially change that to only be active when a connection attempt is happening. Ctrl + F3 could potentially only be activated during a hosting session, but it will need to be global. Alternatively, hosts can change these hotkeys to any combo they wish.

**Comment by Mempler** [comment] 2019-11-28 04:26
@boxerbk How about a Toggle switch if those keys should be enabled or not? Since as for now, I've completely disabled those by editing `keybindings.txt`
Your second taught would be nice too!

**Comment by peppy** [comment] 2019-11-28 04:31
Would highly recommend doing as mentioned – only listening when the keys are valid. Photoshop does a similar thing even when minimised, and it absolutely destroys faith in an application.

Closing this issue for now.

**Closed by peppy** 2019-11-28 04:31 UTC
Labels: input
