### ISSUE TITLE
Clicks in nested context menus don't close the menu correctly

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-framework#2965] opened 2019-11-08 07:57 UTC
When clicking an item in a sub-menu, the whole menu tree should close.

https://streamable.com/3lv90

**Comment by iiSaLMaN** [comment] 2019-11-12 12:05
The underlying issue here is that the logic for closing all menus checks for the item that opened this menu for whether it has the action item: https://github.com/ppy/osu-framework/blob/5af7b335fbc0d8657cd41a7ea422fd5435ab8c66/osu.Framework/Graphics/UserInterface/Menu.cs#L526-L530

I already have a fix for this which is to check if the triggering item is null to allow closing top parent menu, the problem is that it is way hard to test this behaviour as `TestSceneNestedMenus` tests depend on the menu being top-level, and there is no way to change that as `TopLevelMenu` is read-only, is it fine making it non-read-only for the sake of testing it?

**Comment by iiSaLMaN** [comment] 2019-11-12 12:10
Other way to test this cleanly would be refactoring the entire test and create an abstract test scene that provides enough tools for testing the menu, may be time-consuming though.

**Closed** 2019-11-13 05:21 UTC
Labels: bug, pending review, user interface
