### ISSUE TITLE
File chooser breadcrumb control does not handle overflow well

### ISSUE THREAD

**Issue by bdach** [ppy/osu-framework#4704] opened 2021-08-23 16:31 UTC
Follow-up from https://github.com/ppy/osu/pull/14462.

See the following example:

![2021-08-23-181245_861x116_scrot](https://user-images.githubusercontent.com/20418176/130482374-e33bd740-5801-4245-b83e-f3ae7702683e.png)

I can think of a few things that could be done here, such as adding a horizontal scroll or limiting the number of breadcrumbs shown to last N (where N is user-configurable, or somehow calculated automatically). Unsure which is best.

**Comment by frenzibyte** [comment] 2021-08-23 16:41
I think limiting the number of breadcrumbs to last N would be a better choice rather than showing every folder up to `/`, also seems like something that should be calculated automatically based on the breadcrumb area width, rather than being configurable.

**Comment by TPGPL** [comment] 2021-08-23 17:30
duplicate of https://github.com/ppy/osu/issues/9399, but i guess the one from `osu` repo can be closed as this is rather a framework issue

**Comment by bdach** [comment] 2021-08-23 17:34
Thanks, I totally forgot that issue was there already... It *is* a framework issue now, but it wasn't then.

**Comment by frenzibyte** [comment] 2022-11-04 00:57
Resolved in https://github.com/ppy/osu-framework/pull/5496.

**Closed by frenzibyte** 2022-11-04 00:57 UTC
Labels: area:UI
