### ISSUE TITLE
Circle doesnt obey Masking of CircularContainer

### ISSUE THREAD

**Issue by 64ArthurAraujo** [ppy/osu-framework#6067] opened 2023-11-30 14:39 UTC
Differently from other shapes circles doesn't follow the masking of the circular container and appears to be in a square container, basically what i was trying to do is something similar to the lazer's logo triangles but with circles.

```C#
new CircularContainer
{
	Anchor = Anchor.Centre,
        Origin = Anchor.Centre,
        Masking = true,
        Y = 0,
	X = 0,
        Size = Size,
        Children = new Drawable[]
        {
        	new Circle {
                        Anchor = Anchor.TopCentre,
                        Origin = Anchor.TopCentre,
                        Colour = Color4.DarkRed,
                        Y = -12.5f,
                	Size = new Vector2(64, 64)
		}
        }
}
```

![Captura de tela de 2023-11-30 10-53-14](https://github.com/ppy/osu-framework/assets/90941580/16c494f9-182c-4f19-a5dd-62bf98210128)   ![Captura de tela de 2023-11-30 10-53-35](https://github.com/ppy/osu-framework/assets/90941580/dd959683-670b-4673-a2ef-c30328d133ed) ![Captura de tela de 2023-11-30 10-53-50](https://github.com/ppy/osu-framework/assets/90941580/43108d73-5faa-4471-9e29-a67ccaa1dc22)

**Comment by bdach** [comment] 2023-12-01 09:11
Mostly duplicate of #2107. The recommended workaround is to use a `BufferedContainer`.

**Closed by bdach** 2023-12-01 09:11 UTC
