### ISSUE TITLE
Score splitter points display incorrectly when i set French langage  

### ISSUE THREAD

**Issue by EnzoDeg40** [ppy/osu-framework#5529] opened 2022-11-20 11:19 UTC
I don't know if this bug has already been reported, I did not find it in the issues. But `,` are replaced by `?` when i play in French langage. This bug does not exist in other languages such as German or Spanish
![image](https://user-images.githubusercontent.com/35306710/202899017-c6aa71ac-60f4-4df3-a4bd-396fc257c0cd.png)
![image](https://user-images.githubusercontent.com/35306710/202899027-fab3e225-9ee2-45c7-9390-b9574595fd46.png)

**Comment by bdach** [comment] 2022-11-20 11:21
Duplicate of https://github.com/ppy/osu/issues/15135

**Closed by bdach** 2022-11-20 11:21 UTC
