### ISSUE TITLE
Siri breaks audio

### ISSUE THREAD

**Issue by Elepover** [ppy/osu-framework#3750] opened 2020-07-20 03:45 UTC
**Describe the bug:** 

iOS-specific.

When you bring up Siri, osu! is naturally, muted. But when you exit Siri, seems like audio playback was suspended without being resumed, effectively muting the whole game. And the visualizer around osu! cookie just kept spinning in a static shape.

- Music is in "playing" state but progress froze.
- Sound effects doesn't play.
- Pausing and resuming music doesn't help.
- Putting osu! into background and resuming doesn't help.
- Seeking music progress doesn't help.
- Reproduces every time.

**osu!lazer version:** 

`2020.717.0`

Note: I'm using iOS 14 with a new Siri interface, don't know if it reproduces on iOS 13. I think this may apply to all osu! versions and is related to some kind of unhandled events.

**Comment by peppy** [comment] 2020-07-20 03:46
@TimOliver maybe one you'll know something about

**Comment by TimOliver** [comment] 2020-07-20 03:49
Interesting! I have a few devices here running both iOS 13 and 14. I'll have a play with them and see if that's a bug inherent to 14 or not.

Thanks for the heads-up!

**Comment by TimOliver** [comment] 2020-07-20 07:03
@Elepover Hmm, I just tried reproducing it on my iPad runnining iPadOS 13 and my iPod touch running iOS 14. I wasn't able to reproduce it in either. It seems to be fine for me.

Can you please attach a video of the problem happening so I can see the exact steps you're taking that trigger this?

Thanks!

**Comment by Snowmander** [comment] 2020-07-20 13:24
I can reproduce this on my iPad running iOS 14 (beta 2), but not on my iPhone running iOS 13.

Reproduction: open the app, say “hey siri”, and dismiss the new siri popup. Also, the app crashes after it is switched away to the background and then brought back.

**Comment by Elepover** [comment] 2020-07-20 14:33
@TimOliver FYI, my environment is iPadOS 14 (beta 2, `18A5319i`).

And here’s the screen recording:

https://www.icloud.com/iclouddrive/0JvjOy1p-c7VK1ahRkxlzhYUg#RPReplay_Final1595254787

Just opening Siri by holding top button can trigger this.

**Comment by Elepover** [comment] 2020-07-20 14:50
I also found that everything related to “beats” ~~(not to be confused with Dr. Dre)~~ has also stopped working like:

- The bouncy icons on main menu buttons no longer bounces
  - They only tilt
- The blinking input indicator on `TextBox`es doesn’t show up

**Comment by Elepover** [comment] 2020-07-25 01:25
Follow-up: Apple pushed 3rd developer beta of iPadOS 14 a few days ago, didn't affect the bug reproduction. Everything's pretty much the same.

**Comment by TimOliver** [comment] 2020-07-28 04:23
Hi @Elepover! Sorry for the delay! 

Thanks for pre-empting what I was going to ask about if you'd tried it on iPadOS 14 beta 3 yet.

Oh wow! Thanks so much for the video! That's really interesting to see. The fact that osu! itself stops providing visual feedback seems to imply it's not the system simply suppressing the audio from the game itself, but bringing up Siri is actually halting playback of the audio in the game itself, and it's not restoring properly when Siri is dismissed.

That's enough for me to go and have a look at a few potential causes of this. Thanks so much for that!

**Comment by TimOliver** [comment] 2020-10-25 15:32
Hey @Elepover!

Sorry for the delay! I had this in the back of my mind to check this once iOS 14 had hit the public.

Testing it on iOS 14.0.1 on my iPad now, it seems that it's working properly now.

If you've updated to the public version of iOS 14 by this point, can you confirm if it's fixed on your end too?

Thanks!

**Comment by Elepover** [comment] 2020-10-25 23:15
@TimOliver Oh sorry I forgot to test that on previous GM releases of iOS (14/14.0.1). Seems like everything is the same on iPadOS 14.1 (18A8395).

**Closed** 2020-10-26 01:30 UTC
Labels: area:audio, platform:iOS
