### ISSUE TITLE
Null Reference Exception in OsuJsonWebRequest.GetResponseString()

### ISSUE THREAD

**Issue by Neuheit** [ppy/osu-framework#4112] opened 2020-12-27 00:47 UTC
From the latest commit in the osu! dev build, clicking on the multiplayer tab from startup results in the following NRE: 

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=osu.Framework
  StackTrace:
   at osu.Framework.IO.Network.WebRequest.GetResponseString()
```

This throws in line 157 in the `osu.Game.API.APIRequest` class, but I am creating the issue here as it is framework related.

**Comment by bdach** [comment] 2020-12-27 01:00
I cannot reproduce this neither on debug on release, and I'm not sure I understand why this would be a framework bug - and just saying there's a NRE does not help matter much. Please provide more details about your execution environment.

**Comment by Neuheit** [comment] 2020-12-27 02:40
OS: Windows 10 Build 19042
IDE: Visual Studio 2019 Build 16.8.3
.NET: Core 3.1

I figured this is a framework bug because a null ref was thrown from a framework method, which didn't seem intended to me.

**Comment by peppy** [comment] 2020-12-27 03:54
We already discussed this in discord right? Or are you a different user?

Either way, none of us can reproduce this so we need you to provide more details. I would recommend using a local framework reference if required (see https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) and seeing what state the web request is in. If it has a null response, it also likely had an error along the way.

**Comment by Neuheit** [comment] 2020-12-27 08:07
> We already discussed this in discord right? Or are you a different user?

Yes I'm the same user. 

> Either way, none of us can reproduce this so we need you to provide more details. I would recommend using a local framework reference if required (see https://github.com/ppy/osu-framework/wiki/Testing-local-framework-checkout-with-other-projects) and seeing what state the web request is in. If it has a null response, it also likely had an error along the way.

Alright I'll take a look at that, thanks!

**Comment by Firmatorenio** [comment] 2020-12-27 08:25
For the sake of clearing up some confusion, there was another user whom this was discussed with, and _that_ was me.

**Comment by peppy** [comment] 2020-12-27 09:52
Closing this, looks to be behaving as intended.

**Closed by peppy** 2020-12-27 09:52 UTC
Labels: missing details
