### ISSUE TITLE
[iOS/Mac] Possibility to support Metal or atleast Vulkan which can have MoltenVK used to translate to Metal

### ISSUE THREAD

**Issue by ThatsNiceGuy** [ppy/osu-framework#3764] opened 2020-07-24 01:06 UTC
Both of the above would be more efficient on mobile platforms as afaik iOS 13 started to translate OpenGL ES calls into Metal at the software driver level, which can use extra CPU time. Supporting Vulkan (or Metal at the best case) would help remove some of this overhead as with MoltenVK,  Vulkan to Metal translated graphics are much more efficient in most cases. The benefit of this can be seen in DolphiniOS, where the graphics backend internally is Vulkan which is translated to Metal in software and is more efficient than running the OpenGL ES backend.

**Comment by peppy** [comment] 2020-07-24 01:13
This is an eventual goal, either via https://github.com/mellinoe/veldrid or otherwise. Along with direct x and others.

Duplicate of https://github.com/ppy/osu-framework/issues/2119 (and kind of WIP at https://github.com/ppy/osu-framework/issues/2448)

**Closed by peppy** 2020-07-24 01:13 UTC
