### ISSUE TITLE
Video playback starts early after beatmap loads

### ISSUE THREAD

**Issue by dscnnctd** [ppy/osu-framework#2894] opened 2019-10-13 04:09 UTC
Video usually waits for the song to play so that it could be played at the same time. In lazer, this is not being followed correctly as stable does.

**Lazer:**
https://youtu.be/GfhO5y7tL6Q
**Stable:**
https://youtu.be/PBcag-GJmQU

**Comment by smoogipoo** [comment] 2019-10-13 08:05
Duplicate of ppy/osu#6101. Also wrong repository.

**Closed by smoogipoo** 2019-10-13 08:05 UTC
