### ISSUE TITLE
High CPU usage while minimized

### ISSUE THREAD

**Issue by DCNick3** [ppy/osu-framework#3151] opened 2020-01-02 08:24 UTC
**Describe the bug:** 

When osu is minimized, even though it's not doing anything, it consumes a lot of CPU time (about 60% of one core). I use it on a laptop and this affects battery life pretty hard.

**Screenshots or videos showing encountered issue:** 

![Screenshot_20200102_112313](https://user-images.githubusercontent.com/10363282/71657754-4536aa00-2d52-11ea-8ab2-576c18fc9f93.png)

**osu!lazer version:** 
Git revision `beb8e72e1`

**Comment by Nabile-Rahmani** [comment] 2020-01-23 10:02
It might not be applicable here but just in case: beware of solely relying on `SDL_RenderPresent()` for taking care of sleeping the video thread if you enable vsync, as I found out this call will not wait for vertical synchronisation when the window is minimised (`SDL_WINDOW_{MINIMIZED,HIDDEN}`).

I had to keep track of the elapsed time and subtract that by the display's refresh rate to approximate an acceptable Thread.Sleep duration between frames to not burn the CPU when minimised. Thanks SDL.

**Comment by nisheri-ascar** [comment] 2024-11-18 06:37
hello, this issue should be closed now. it is not an issue on newer version of osu!
![image](https://github.com/user-attachments/assets/0ec7f30a-10ad-400e-9769-39007c77ceac)

**Comment by smoogipoo** [comment] 2024-11-18 06:41
It's still an issue. There have been no changes to fix it and we have reproduced.

**Comment by peppy** [comment] 2024-11-18 08:03
I think the *linux specific* usage should be fixed (I can't reproduce on macOS). It does seem to be windows specific as far as I can tell? (investigating at https://github.com/ppy/osu/discussions/30192)

**Comment by smoogipoo** [comment] 2024-11-18 08:08
What would've changed linux/macOS specifically? I believe the only issue there is that https://github.com/ppy/osu-framework/pull/6392 hasn't been merged yet, but once it is it'll likely experience the same.

**Comment by peppy** [comment] 2024-11-18 08:13
Not too sure, this was open since *before SDL* 😅

**Closed** 2024-12-10 15:19 UTC
Labels: type:performance, platform:linux
