### ISSUE TITLE
libbass.so not being loaded under Linux despise being on the library loading path

### ISSUE THREAD

**Issue by Tevo45** [ppy/osu-framework#2189] opened 2019-02-26 02:45 UTC
`LD_LIBRARY_PATH` is set to the build folder, and both `libbass.so` and `libbass_fx.so` are present on said folder. Setting `LD_DEBUG=libs` shows that the osu!framework doesn't seem to attempt loading such libraries (messages like `find library=libbass.so` are never logged to the console, meaning those files are never requested), whereas on an older, known-good version of the framework (2019.122.0) such files are successfully found and loaded.
Moving `libbass.so` and `libbass_fx.so` to one of the default library locations, such as `/usr/bin` has no effect whatsoever.

**Steps to reproduce:**
1. Build and try to run any osu!framework-dependent project with the latest framework build on a Linux system
2. Application will crash with a `System.DllNotFoundException` claiming that it wasn't possible to load shared library 'bass' or one of it's dependencies

**Comment by peppy** [comment] 2019-02-26 09:27
Could you please git bisect and locate when this regressed?

**Comment by mwkroening** [comment] 2019-02-27 21:53
I think I have the same issue on my system, although installing libbass and libbass_fx with my distro's package manager works around it.

The issue began appearing with 2019.214.0. With 2019.131.0 the workaround of natively installing libbass_fx was not necessary.

I will try tracking down the commit which introduced this regression.

**Comment by mwkroening** [comment] 2019-02-27 22:32
Git-bisecting osu gave:

```bash
e8aed6b68641b2d033267d0d0384ec2f17691229 is the first bad commit
commit e8aed6b68641b2d033267d0d0384ec2f17691229
Author: Dean Herbert <pe@ppy.sh>
Date:   Fri Feb 8 17:38:18 2019 +0900

    Update framework

:040000 040000 12aea5c5b80205681e36f90f9da3e9c4db2edb26 eb04d6ca2437e4269b94a7fabc8fa3c1a79c5f56 M	osu.Game
:100644 100644 e00c4fcf78946c29af06878172ca735e976f5993 0d8a7e3a34468873acbe1392013dc4d11b9695e2 M	osu.iOS.props
```

Looking at the commit the regression was introduced when upgrading osu-framework from 2019.205.0 to 2019.208.1.

**Comment by mwkroening** [comment] 2019-02-27 22:36
Sometime in the next days I will try to track down the affecting commit in the framework.

**Comment by GurovRoman** [comment] 2019-02-27 23:07
For some reason ppy.osu.framework.nativelibs comes with 32-bit shared libraries, which didn't work for me. I had to manually replace with x64 ones from BASS' website.

**Comment by peppy** [comment] 2019-02-28 00:47
thanks for tracing this down, i'll look into the incorrect libraries.

**Comment by peppy** [comment] 2019-03-01 11:06
@GurovRoman are you able to test whether it still works if you put the 64bit libraries inside `x64` (and move the x86 ones to `x86`)?

**Comment by GurovRoman** [comment] 2019-03-01 15:16
I published and put libraries in the respective folders but it didn't seem to search for them there. With LD_LIBRARY_PATH set to osu directory, it scans `x86_64`, though.

**Comment by peppy** [comment] 2019-03-01 15:36
so `x86_64` and `x86`?

**Comment by GurovRoman** [comment] 2019-03-01 18:00
Not sure about `x86` but these directories are scanned only when specifying LD_LIBRARY_PATH. Game root is scanned anyway. It is preferable for the game to run out-of-the-box

**Comment by miterosan** [comment] 2019-03-02 10:49
I had the problem that the libraries were scanned, but then ignored. But changing the permission of the .so files to read,execute did fix this for me... That and also adding the x64 directory to LD_LIBRARY_PATH.

**Comment by GurovRoman** [comment] 2019-03-02 11:20
Execute permissions on a shared library are not needed because you don't execute it. All the other rights are set correctly

**Comment by peppy** [comment] 2019-03-04 11:36
Would be grateful if someone with a linux system can PR a fix for this, moving libraries to their correct x86/x64 locations.

**Comment by mwkroening** [comment] 2019-03-06 11:53
On my machine (Arch Linux x64) the problem persists.

Running

```bash
git clone git@github.com:ppy/osu.git
git clone git@github.com:ppy/osu-framework.git

cd osu

CSPROJ="osu.Game/osu.Game.csproj"
SLN="osu.sln"

dotnet remove $CSPROJ package ppy.osu.Framework;
dotnet sln $SLN add ../osu-framework/osu.Framework/osu.Framework.csproj ../osu-framework/osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj;
dotnet add $CSPROJ reference ../osu-framework/osu.Framework/osu.Framework.csproj

LD_LIBRARY_PATH="$(pwd)/osu.Desktop/bin/Debug/netcoreapp2.2" dotnet run --project osu.Desktop
```

just resulted in:

```bash
Cloning into 'osu'...
[...]
Cloning into 'osu-framework'...
[...]
info : Removing PackageReference for package 'ppy.osu.Framework' from project 'osu.Game/osu.Game.csproj'.
Project `../osu-framework/osu.Framework/osu.Framework.csproj` added to the solution.
Project `../osu-framework/osu.Framework.NativeLibs/osu.Framework.NativeLibs.csproj` added to the solution.
Reference `..\..\osu-framework\osu.Framework\osu.Framework.csproj` added to the project.
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning :    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf) [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever) [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning :    at LibGit2Sharp.Repository.Discover(String startingPath) [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning :    at Microsoft.Build.Tasks.Git.GitOperations.LocateRepository(String directory) in /_/src/Microsoft.Build.Tasks.Git.Operations/GitOperations.cs:line 26 [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-18618-05/build/Microsoft.Build.Tasks.Git.targets(20,5): warning :    at Microsoft.Build.Tasks.Git.RepositoryTasks.LocateRepository(LocateRepository task) in /_/src/Microsoft.Build.Tasks.Git.Operations/RepositoryTasks.cs:line 58 [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
/home/mkroening/.nuget/packages/microsoft.sourcelink.common/1.0.0-beta2-18618-05/build/Microsoft.SourceLink.Common.targets(53,5): warning : Source control information is not available - the generated source link is empty. [/home/mkroening/Development/osu-linux/osu-framework/osu.Framework/osu.Framework.csproj]
[runtime:verbose] 3/6/19 11:50:04 AM: GL Initialized
[runtime:verbose] 3/6/19 11:50:04 AM: GL Version:                 3.0 Mesa 18.3.4
[runtime:verbose] 3/6/19 11:50:04 AM: GL Renderer:                Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2)
[runtime:verbose] 3/6/19 11:50:04 AM: GL Shader Language version: 1.30
[runtime:verbose] 3/6/19 11:50:04 AM: GL Vendor:                  Intel Open Source Technology Center
[runtime:verbose] 3/6/19 11:50:04 AM: GL Extensions:              GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_fragment_shader_interlock GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_EXT_shader_samples_identical GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_shader_framebuffer_fetch_non_coherent GL_INTEL_shader_atomic_float_minmax
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font OpenSans...
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font FontAwesome...
[runtime:verbose] 3/6/19 11:50:04 AM: Unhandled exception has been denied .
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font FontAwesome!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font osuFont...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font osuFont!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-Medium...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-Medium!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-MediumItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font OpenSans!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font OpenSans-Bold...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-MediumItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Noto-Basic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font OpenSans-Bold!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font OpenSans-Italic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font OpenSans-Italic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font OpenSans-BoldItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Noto-Basic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Noto-Hangul...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font OpenSans-BoldItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Noto-Hangul!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Noto-CJK-Basic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Noto-CJK-Basic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Noto-CJK-Compatibility...
[runtime:error] 3/6/19 11:50:04 AM: An unhandled error has occurred.
[runtime:error] 3/6/19 11:50:04 AM: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
[runtime:error] 3/6/19 11:50:04 AM: at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
[runtime:error] 3/6/19 11:50:04 AM: at ManagedBass.Bass.get_DeviceCount()
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Audio.AudioManager.getAllDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 193
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 300
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Audio.AudioManager.setAudioDevice(String preferredDevice) in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 203
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Audio.AudioManager.<>c__DisplayClass28_0.<onDeviceChanged>b__0() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 144
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Threading.ScheduledDelegate.RunTask() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 283
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Threading.Scheduler.Update() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 154
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Threading.GameThread.ProcessFrame() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 137
[runtime:error] 3/6/19 11:50:04 AM: at osu.Framework.Threading.GameThread.runWork() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 110
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Noto-CJK-Compatibility!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-Regular...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-Regular!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-RegularItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-RegularItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-SemiBold...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-SemiBold!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-SemiBoldItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-SemiBoldItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-Bold...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-Bold!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-BoldItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-BoldItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-Light...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-Light!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-LightItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-LightItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-Black...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-Black!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Exo2.0-BlackItalic...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Exo2.0-BlackItalic!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Venera...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Venera!
[runtime:debug] 3/6/19 11:50:04 AM: Loading Font Venera-Light...
[runtime:debug] 3/6/19 11:50:04 AM: Loaded Font Venera-Light!
[runtime:verbose] 3/6/19 11:50:05 AM: Unhandled exception has been denied .
[runtime:error] 3/6/19 11:50:05 AM: An unhandled error has occurred.
[runtime:error] 3/6/19 11:50:05 AM: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
[runtime:error] 3/6/19 11:50:05 AM: at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
[runtime:error] 3/6/19 11:50:05 AM: at ManagedBass.Bass.get_DeviceCount()
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Audio.AudioManager.getAllDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 193
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 300
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 127
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Threading.ScheduledDelegate.RunTask() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 283
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Threading.Scheduler.Update() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 154
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Threading.GameThread.ProcessFrame() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 137
[runtime:error] 3/6/19 11:50:05 AM: at osu.Framework.Threading.GameThread.runWork() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 110
[runtime:verbose] 3/6/19 11:50:06 AM: Unhandled exception has been denied .
[runtime:error] 3/6/19 11:50:06 AM: An unhandled error has occurred.
[runtime:error] 3/6/19 11:50:06 AM: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
[runtime:error] 3/6/19 11:50:06 AM: at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
[runtime:error] 3/6/19 11:50:06 AM: at ManagedBass.Bass.get_DeviceCount()
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Audio.AudioManager.getAllDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 193
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 300
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Audio.AudioManager.<>c__DisplayClass26_0.<.ctor>b__3() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 127
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Threading.ScheduledDelegate.RunTask() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 283
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Threading.Scheduler.Update() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 154
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Threading.GameThread.ProcessFrame() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 137
[runtime:error] 3/6/19 11:50:06 AM: at osu.Framework.Threading.GameThread.runWork() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 110
[runtime:debug] 3/6/19 11:50:06 AM: New TextureAtlas initialised 3x3
Console output is being limited. Please check runtime.log for full logs.

Unhandled Exception: System.DllNotFoundException: Unable to load shared library 'bass' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libbass: cannot open shared object file: No such file or directory
   at ManagedBass.Bass.GetDeviceInfo(Int32 Device, DeviceInfo& Info)
   at ManagedBass.Bass.get_DeviceCount()
   at osu.Framework.Audio.AudioManager.getAllDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 193
   at osu.Framework.Audio.AudioManager.updateAvailableAudioDevices() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 300
   at osu.Framework.Audio.AudioManager.setAudioDevice(String preferredDevice) in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 203
   at osu.Framework.Audio.AudioManager.<>c__DisplayClass28_0.<onDeviceChanged>b__0() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Audio/AudioManager.cs:line 144
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 283
   at osu.Framework.Threading.Scheduler.Update() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 154
   at osu.Framework.Threading.GameThread.ProcessFrame() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 137
   at osu.Framework.Threading.GameThread.runWork() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at osu.Framework.Platform.GameHost.<>c__DisplayClass82_0.<handleException>b__0() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Platform/GameHost.cs:line 267
   at osu.Framework.Threading.ScheduledDelegate.RunTask() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 283
   at osu.Framework.Threading.Scheduler.Update() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/Scheduler.cs:line 154
   at osu.Framework.Threading.GameThread.ProcessFrame() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/GameThread.cs:line 137
   at osu.Framework.Threading.InputThread.RunUpdate() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Threading/InputThread.cs:line 28
   at osu.Framework.Platform.GameHost.<Run>b__103_1(Object <p0>, FrameEventArgs <p1>) in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Platform/GameHost.cs:line 520
   at osuTK.GameWindow.RaiseUpdateFrame(Stopwatch watch, Double elapsed, Double& timestamp)
   at osuTK.GameWindow.DispatchUpdateFrame(Stopwatch watch)
   at osuTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at osu.Framework.Platform.GameWindow.Run() in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Platform/GameWindow.cs:line 258
   at osu.Framework.Platform.GameHost.Run(Game game) in /home/mkroening/Development/osu-linux/osu-framework/osu.Framework/Platform/GameHost.cs:line 531
   at osu.Desktop.Program.Main(String[] args) in /home/mkroening/Development/osu-linux/osu/osu.Desktop/Program.cs:line 46
```

**Comment by GurovRoman** [comment] 2019-03-06 12:09
That's weird. Could you also add the LD_DEBUG=libs variable and find what folders it scans for libbass.so?

**Comment by mwkroening** [comment] 2019-03-06 13:15
I uploaded the output with `LD_DEBUG=libs` to [pastebin.com](https://pastebin.com/RPbyNnm8).

Copying `libbass.so` and `libbass_fx.so` from `osu-framework/osu.Framework.NativeLibs/x86_64/` to `osu/osu.Desktop/bin/Debug/netcoreapp2.2/` does help.

Sidenote:
`osu/osu.Desktop/bin/Debug/netcoreapp2.2/` does contain `libbass.a` and `libbass.dylib` (also `libbass_fx.a` and `libbass_fx.dylib`).
Inspecting them with `file` gives:
```bash
[mkroening netcoreapp2.2]$ file libbass.a 
libbass.a: Mach-O universal binary with 6 architectures: [armv7:current ar archive random library] [armv7s:current ar archive random library] [armv6:current ar archive random library] [i386] [x86_64] [arm64:current ar archive random library]
[mkroening netcoreapp2.2]$ file libbass.dylib 
libbass.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit x86_64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>] [i386:Mach-O i386 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS>]
```

**Comment by mwkroening** [comment] 2019-03-06 13:31
Copying `libbass.so` and `libbass_fx.so` to `osu/osu.Desktop/bin/Debug/netcoreapp2.2/x86_64` does work as well (the folder does not exist by default).

**Comment by GurovRoman** [comment] 2019-03-06 13:38
Okay, got that. It was naive of me to think that it copies the whole directory. Will look into configs now. It would be really good if you could check that fix before it gets merged, because I can't build the framework myself.

**Comment by mwkroening** [comment] 2019-03-06 13:45
I was going to yesterday, but https://github.com/ppy/osu-framework/issues/2218 got in the way.

Will surely do so next time.

@peppy, could you reopen this issue for now?

I think currently Linux (x86) is also broken, since the libbass shared libraries in `x86/` are not being copied as well.

**Comment by GurovRoman** [comment] 2019-03-06 13:53
I think I already fixed it, but need to create a new PR

**Closed** 2019-03-06 15:57 UTC
Labels: compatibility, linux
