### ISSUE TITLE
Unable to open more than one osu!framework based project at the same time

### ISSUE THREAD

**Issue by anispwyn** [ppy/osu-framework#6127] opened 2024-01-11 12:07 UTC
when you're opening something like osu!lazer, [fluXis](https://github.com/TeamFluXis/fluXis) would refuse to open and vise versa (it report STATUS_SUCCESS after closed)

for some reason, you can open [Vigette](https://github.com/vignetteapp/vignette) and osu!lazer (or fluXis) just fine, probably because it(Vigette) is using the old version of the framework

you can watch an example video here:
https://streamable.com/yxxxtb

tested using:
osu!lazer [2023.1231.0](https://github.com/ppy/osu/releases/tag/2023.1231.0)
fluXis [Hotfix v2024.1.1](https://github.com/TeamFluXis/fluXis/releases/tag/2024.1.1)

environment:
windows 11 enterprise insider preview build 26020
r5 6600h
rtx 3050ti

**Comment by bdach** [comment] 2024-01-11 12:16
> probably because it(Vigette) is using the old version of the framework

No. Root cause will be in here: https://github.com/TeamFluXis/fluXis/blob/5890fbe6487e3323c379a83454f935d5a0f4f346/fluXis.Desktop/Program.cs#L25-L45

fluxis instance thinks the previously opened osu! instance is the primary instance of itself rather than a completely different framework app.

The ipc port probably needs to be configurable per framework app:

https://github.com/ppy/osu-framework/blob/master/osu.Framework/Platform/DesktopGameHost.cs#L18

**Closed** 2024-01-15 21:16 UTC
Labels: area:configuration, priority:1
